/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AiAssistant: typeof import('./src/components/AiAssistant.vue')['default']
    CircleCard: typeof import('./src/components/CircleCard.vue')['default']
    CommentItem: typeof import('./src/components/CommentItem.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    ReportDialog: typeof import('./src/components/ReportDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
  }
}
