/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AiAssistant: typeof import('./src/components/AiAssistant.vue')['default']
    CircleCard: typeof import('./src/components/CircleCard.vue')['default']
    CommentItem: typeof import('./src/components/CommentItem.vue')['default']
    EditPostDialog: typeof import('./src/components/EditPostDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    ReportDialog: typeof import('./src/components/ReportDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareChainDialog: typeof import('./src/components/ShareChainDialog.vue')['default']
    ShareSheet: typeof import('./src/components/ShareSheet.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanIcon: typeof import('vant/es')['Icon']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanLoading: typeof import('vant/es')['Loading']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
