/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiReportCard: typeof import('./src/components/AiReportCard.vue')['default']
    ChartCard: typeof import('./src/components/ChartCard.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    HexagonLogo: typeof import('./src/components/HexagonLogo.vue')['default']
    RiskLevelTag: typeof import('./src/components/RiskLevelTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StatusTag: typeof import('./src/components/StatusTag.vue')['default']
  }
}
